# Generated by Django 5.0.4 on 2024-09-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_profile_bank_account_number_profile_bank_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentrecord",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="employment_documents/"
            ),
        ),
    ]
