# Generated by Django 5.0.4 on 2024-09-24 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="short_code",
            new_name="Employee_Code",
        ),
    ]
