# Generated by Django 5.0.4 on 2024-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_rename_short_code_profile_employee_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalqualification",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="qualifications/"),
        ),
    ]
