# Generated by Django 5.0.4 on 2024-10-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_educationalqualification_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(
                blank=True, default=False, max_length=100, null=True
            ),
        ),
    ]
