# Generated by Django 5.0.4 on 2024-11-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_profile_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
