# Generated by Django 5.0.4 on 2024-10-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uan_number",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="UAN No."
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="PAN No."
                    ),
                ),
                (
                    "esic_number",
                    models.CharField(
                        max_length=17, unique=True, verbose_name="ESIC No."
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["pan_number"],
            },
        ),
    ]
