# Generated by Django 5.0.4 on 2024-10-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0006_applicant_profile"),
        ("compliance", "0003_alter_compliance_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliance",
            name="applicant",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance",
                to="applicant.applicant",
            ),
        ),
    ]
