# Generated by Django 5.0.4 on 2024-10-18 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0006_applicant_profile"),
        ("compliance", "0005_alter_compliance_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
            ),
        ),
        migrations.DeleteModel(
            name="Compliance",
        ),
    ]
