# Generated by Django 5.0.4 on 2024-10-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0009_alter_employee_applicant"),
        ("users", "0013_educationalqualification_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
