# Generated by Django 5.0.4 on 2024-10-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee_deduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pf_deduction",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="PF_Deduction"
                    ),
                ),
                (
                    "asic_deduction",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ASIC_Deduction"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pf_emp_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="PF (Employers Contribution)",
                    ),
                ),
                (
                    "esic_emp_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="ESIC (Employers Contribution)",
                    ),
                ),
                (
                    "mediclaim",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Mediclaim"
                    ),
                ),
                (
                    "gratuity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gratuity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Basic Salary"
                    ),
                ),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="HRA"
                    ),
                ),
                (
                    "special_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Special Allowance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeCTC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compensation.employeecontribution",
                        verbose_name="Employer's Contribution",
                    ),
                ),
                (
                    "deduction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compensation.employee_deduction",
                        verbose_name="Employee Deduction",
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compensation.employeesalary",
                        verbose_name="Employee Salary",
                    ),
                ),
            ],
        ),
    ]
