# Generated by Django 5.0.4 on 2024-10-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0006_applicant_profile"),
        ("compensation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeectc",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
            ),
        ),
        migrations.AlterField(
            model_name="employeectc",
            name="contribution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="compensation.employeecontribution",
            ),
        ),
        migrations.AlterField(
            model_name="employeectc",
            name="deduction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="compensation.employee_deduction",
            ),
        ),
        migrations.AlterField(
            model_name="employeectc",
            name="salary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="compensation.employeesalary",
            ),
        ),
    ]
