# Generated by Django 5.0.4 on 2024-10-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "compensation",
            "0002_employeectc_applicant_alter_employeectc_contribution_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employeectc",
            name="created_at",
            field=models.DateTimeField(default="2023-01-01 00:00:00"),
        ),
    ]
