# Generated by Django 5.0.4 on 2024-10-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compensation", "0003_employeectc_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeectc",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
