# Generated by Django 5.0.4 on 2024-10-18 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compensation", "0005_compliance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Compliance",
        ),
    ]
