# Generated by Django 5.0.4 on 2024-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_passed", models.CharField(max_length=100)),
                ("year_of_passing", models.DateField()),
                ("school_college_university", models.CharField(max_length=255)),
                ("subjects", models.CharField(max_length=255)),
                ("division", models.CharField(max_length=50)),
            ],
        ),
    ]
