# Generated by Django 5.0.4 on 2024-09-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0002_educationalqualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalqualification",
            name="year_of_passing",
            field=models.IntegerField(),
        ),
    ]
