# Generated by Django 5.0.4 on 2024-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0004_languageproficiency"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalqualification",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="qualifications/"),
        ),
    ]
