# Generated by Django 5.0.4 on 2024-09-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0005_educationalqualification_document"),
        ("users", "0010_employmentrecord_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
