# Generated by Django 5.0.4 on 2024-11-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0006_applicant_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
