# Generated by Django 5.0.4 on 2024-11-12 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applicant", "0007_applicant_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="end_date",
        ),
    ]
